cmake_minimum_required(VERSION 3.8)
project(dracoviloc_ekf)
find_package(ament_cmake REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(rclcpp REQUIRED)
add_executable(ekf_node src/ekf_node.cpp)
ament_target_dependencies(ekf_node geometry_msgs rclcpp)
target_link_libraries(ekf_node Eigen3::Eigen)
install(TARGETS ekf_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_package()
