<?xml version="1.0"?>
<package format="3">
  <name>dracoviloc_description</name>
  <version>0.1.0</version>
  <description>Single FAIRINO FR3/AE3C robot description for DracoViLoc.</description>
  <maintainer email="maintainer@example.com">DracoViLoc</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>fairino_hardware</exec_depend>
  <exec_depend>hardware_interface</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
