<?xml version="1.0"?>
<package format="3">
  <name>dracoviloc_bringup</name>
  <version>0.1.0</version>
  <description>Simulation and hardware bringup for DracoViLoc.</description>
  <maintainer email="maintainer@example.com">DracoViLoc</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>dracoviloc_description</exec_depend>
  <exec_depend>dracoviloc_odas</exec_depend>
  <exec_depend>dracoviloc_moveit_config</exec_depend>
  <exec_depend>dracoviloc_tracking</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <depend>rclcpp</depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
